apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config-2
  namespace: dev

data:
  DATABASE_URL: "mysql://testuser2:testpass2@mysql-server:3306/testdb2"
  API_KEY: "test-api-key-2"
  LOG_LEVEL: "error"
  CACHE_ENABLED: "false"
